package com.trading.common.messaging;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Price update message from Mock M7 (exchange) to Gateway.
 *
 * <p>In real trading systems, exchanges broadcast price updates (often called "market data" or
 * "price ticks") to all connected systems. These are typically:
 *
 * <ul>
 *   <li>High frequency (multiple times per second)
 *   <li>Broadcast to all subscribers (pub/sub pattern)
 *   <li>Contain delta information (change from previous price)
 * </ul>
 *
 * <p>Message flow: Mock M7 → prices.topic → Gateway → WebSocket → Browser
 *
 * @param region Trading region (e.g., "NORTH", "SOUTH")
 * @param price Current price per MWh
 * @param currency Currency code (e.g., "EUR", "NGN")
 * @param changePercent Percentage change from previous price
 * @param timestamp When this price was generated by the exchange
 */
public record PriceUpdate(
    String region,
    BigDecimal price,
    String currency,
    double changePercent,
    Instant timestamp) {

  public PriceUpdate {
    if (region == null || region.isBlank()) {
      throw new IllegalArgumentException("region cannot be null or blank");
    }
    if (price == null) {
      throw new IllegalArgumentException("price cannot be null");
    }
    if (currency == null || currency.isBlank()) {
      throw new IllegalArgumentException("currency cannot be null or blank");
    }
    if (timestamp == null) {
      timestamp = Instant.now();
    }
  }
}
