package com.trading.priceMonitor.model;

import com.trading.common.Region;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import java.math.BigDecimal;

/**
 * Order submitted by a client via WebSocket.
 *
 * <p>Received from frontend via STOMP at /app/order. Contains all information needed to place a
 * trade in the electricity market.
 *
 * @param orderId Unique identifier generated by the client (UUID)
 * @param region Trading region - must be one of: NORTH, SOUTH, EAST, WEST
 * @param price Limit price in EUR/MWh (0.01 - 500.00)
 * @param type Order type: "BUY" or "SELL"
 * @param quantity Amount in MWh (0.1 - 1000.00)
 */
public record Order(
    @NotBlank(message = "Order ID cannot be blank") String orderId,
    @NotNull(message = "Region cannot be null. Valid values: NORTH, SOUTH, EAST, WEST")
        Region region,
    @NotNull(message = "Price cannot be null")
        @DecimalMin(value = "0.01", message = "Price must be at least 0.01 EUR/MWh")
        @DecimalMax(value = "500.00", message = "Price cannot exceed 500.00 EUR/MWh")
        BigDecimal price,
    @NotBlank(message = "Type cannot be blank")
        @Pattern(regexp = "^(BUY|SELL)$", message = "Type must be either 'BUY' or 'SELL'")
        String type,
    @NotNull(message = "Quantity cannot be null")
        @DecimalMin(value = "0.1", message = "Quantity must be at least 0.1 MWh")
        @DecimalMax(value = "1000.00", message = "Quantity cannot exceed 1000.00 MWh")
        BigDecimal quantity) {}
