package com.trading.priceMonitor.model;

import java.math.BigDecimal;

/**
 * Order submitted by a client via WebSocket.
 *
 * <p>Received from frontend via STOMP at /app/order. Contains all information needed to place a
 * trade in the electricity market.
 *
 * @param orderId Unique identifier generated by the client (UUID)
 * @param region Trading region (e.g., "NORTH", "SOUTH", "EAST", "WEST")
 * @param price Limit price in EUR/MWh
 * @param type Order type: "BUY" or "SELL"
 * @param quantity Amount in MWh (0.1 - 1000)
 */
public record Order(
    String orderId, String region, BigDecimal price, String type, BigDecimal quantity) {

  public Order {
    if (orderId == null || orderId.isBlank()) {
      throw new IllegalArgumentException("Order ID cannot be null or blank");
    }
    if (region == null || region.isBlank()) {
      throw new IllegalArgumentException("Region cannot be null or blank");
    }
    if (price == null) {
      throw new IllegalArgumentException("Price cannot be null");
    }
    if (type == null || type.isBlank()) {
      throw new IllegalArgumentException("Type cannot be null or blank");
    }
    if (quantity == null) {
      throw new IllegalArgumentException("Quantity cannot be null");
    }
  }
}
